version: '3'
services: 

  database: 
    build: ./database
    ports: 
      - 3306:3306

  backend: 
    build: ./backend
    depends_on:
      - database
    links: 
      - database
    ports:
      - 3000:3000
    
  frontend:
    build: ./frontend # Ruta a la carpeta frontend
    ports:
      - 8080:8080