CREATE DATABASE IF NOT EXISTS employeesdb;
USE employeesdb;

CREATE TABLE IF NOT EXISTS employees(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) DEFAULT NULL,
    salary FLOAT DEFAULT NULL,
    PRIMARY KEY(id)
);
