name: Build and Deploy Applicationn 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@master
    
      - name: Check Linter
        run: |
           cd backend && npm install && npm run lint
        continue-on-error: true #Continua a pesar de los errores del linter

      - name: Build and run 
        run: |
           docker compose up -d