name: Build and Deploy Applicationn 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@master
    
      - name: Check Linter
        run: |
           npm --prefix ./backend run lint

      - name: Build and run 
        run: |
           docker compose up -d