name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
           npm install
        working-directory: backend
    

      - name: Check Linter
        run: |
           npm --prefix ./backend run lint

      - name: Checkout code
        uses: actions/checkout@master

      - name: Build and run 
        run: |
           docker compose up -d